# Generated by Django 6.0.2 on 2026-02-18 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrera",
            fields=[
                ("idcarrera", models.AutoField(primary_key=True, serialize=False)),
                ("nombrecarrera", models.CharField(max_length=100, null=True)),
                ("duracionvalor", models.IntegerField(null=True)),
                ("duracionunidad", models.CharField(max_length=20, null=True)),
                ("nivelacademico", models.CharField(max_length=50, null=True)),
            ],
            options={
                "db_table": "carrera",
            },
        ),
        migrations.CreateModel(
            name="EvaluacionVocacional",
            fields=[
                ("idevaluacion", models.AutoField(primary_key=True, serialize=False)),
                ("fecharealizacion", models.DateTimeField(auto_now_add=True)),
                ("puntajetotal", models.IntegerField(default=0)),
                (
                    "idusuario",
                    models.ForeignKey(
                        db_column="idusuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "evaluacionvocacional",
            },
        ),
        migrations.CreateModel(
            name="RecomendacionCarrera",
            fields=[
                (
                    "idrecomendacion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "porcentajeafinidad",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("justificacion", models.TextField(null=True)),
                ("fecharecomendacion", models.DateTimeField(null=True)),
                ("idprioridad", models.IntegerField(blank=True, null=True)),
                (
                    "idcarrera",
                    models.ForeignKey(
                        db_column="idcarrera",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluaciones.carrera",
                    ),
                ),
                (
                    "idevaluacion",
                    models.ForeignKey(
                        db_column="idevaluacion",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluaciones.evaluacionvocacional",
                    ),
                ),
            ],
            options={
                "db_table": "recomendacincarrera",
            },
        ),
        migrations.CreateModel(
            name="RespuestaEvaluacion",
            fields=[
                ("idrespuesta", models.AutoField(primary_key=True, serialize=False)),
                ("idpregunta", models.IntegerField(default=0)),
                ("respuesta", models.TextField(null=True)),
                (
                    "idevaluacion",
                    models.ForeignKey(
                        db_column="idevaluacion",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluaciones.evaluacionvocacional",
                    ),
                ),
            ],
            options={
                "db_table": "respuestasevaluacion",
            },
        ),
    ]
