# Generated by Django 6.0.2 on 2026-02-26 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilVocacional',
            fields=[
                ('idperfil', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'perfilvocacional',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('idpregunta', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
            ],
            options={
                'db_table': 'pregunta',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('perfil_resultado', models.ForeignKey(blank=True, db_column='idperfil', null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluaciones.perfilvocacional')),
            ],
            options={
                'db_table': 'evaluacion',
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('idopcion', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('idpregunta', models.ForeignKey(db_column='idpregunta', on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='evaluaciones.pregunta')),
            ],
            options={
                'db_table': 'opcionrespuesta',
            },
        ),
        migrations.CreateModel(
            name='RespuestaUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluaciones.evaluacion')),
                ('opcion_seleccionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.opcionrespuesta')),
            ],
            options={
                'db_table': 'respuestausuario',
            },
        ),
    ]
