# Generated by Django 6.0.2 on 2026-03-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_perfilvocacional_pregunta_evaluacion_opcionrespuesta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomendacioncarrera',
            name='idcarrera',
        ),
        migrations.RemoveField(
            model_name='evaluacionvocacional',
            name='idusuario',
        ),
        migrations.RemoveField(
            model_name='recomendacioncarrera',
            name='idevaluacion',
        ),
        migrations.RemoveField(
            model_name='respuestaevaluacion',
            name='idevaluacion',
        ),
        migrations.DeleteModel(
            name='Carrera',
        ),
        migrations.DeleteModel(
            name='RecomendacionCarrera',
        ),
        migrations.DeleteModel(
            name='EvaluacionVocacional',
        ),
        migrations.DeleteModel(
            name='RespuestaEvaluacion',
        ),
    ]
