# Generated by Django 6.0.2 on 2026-03-11 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_remove_recomendacioncarrera_idcarrera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestausuario',
            name='pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.pregunta'),
        ),
        migrations.AddConstraint(
            model_name='respuestausuario',
            constraint=models.UniqueConstraint(fields=('evaluacion', 'pregunta'), name='respuesta_unica_por_pregunta'),
        ),
    ]
