# Generated by Django 6.0.2 on 2026-02-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("idusuario", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, null=True)),
                ("apellido", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(max_length=100, null=True, unique=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("fechanacimiento", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="usuarios_usuario_set", to="auth.group"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="usuarios_usuario_set",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "db_table": "usuario",
            },
        ),
    ]
